from core.urban_generator.demography.age_allocation import (
    DEFAULT_MAX_AGE_ALLOCATION_BUILDINGS,
    DEFAULT_MAX_AGE_GROUPS,
    AgeGroupAllocationError,
    AgeGroupAllocationResult,
    AgeGroupAllocationTotal,
    AgeGroupAllocator,
    AgeGroupPopulation,
    BuildingAgeGroupAllocation,
)
from core.urban_generator.demography.allocation import (
    DEFAULT_MAX_POPULATION_ALLOCATION_BUILDINGS,
    BuildingPopulationAllocation,
    PopulationAllocationDiagnostics,
    PopulationAllocationError,
    PopulationAllocationResult,
    PopulationAllocationStatus,
    PopulationAllocator,
)
from core.urban_generator.demography.capacity import (
    DEFAULT_MAX_RESIDENTIAL_CAPACITY_SUBJECTS,
    ResidentialBuildingCapacity,
    ResidentialCapacityCalculator,
    ResidentialCapacityError,
    ResidentialCapacityResult,
    ResidentialCapacitySubject,
)
from core.urban_generator.demography.config import (
    AgeGroupShare,
    DemographicScenario,
    DemographicScenarioError,
    PopulationTarget,
    PopulationTargetKind,
)

__all__ = [
    "AgeGroupAllocationError",
    "AgeGroupAllocationResult",
    "AgeGroupAllocationTotal",
    "AgeGroupAllocator",
    "AgeGroupPopulation",
    "AgeGroupShare",
    "BuildingAgeGroupAllocation",
    "BuildingPopulationAllocation",
    "DEFAULT_MAX_AGE_ALLOCATION_BUILDINGS",
    "DEFAULT_MAX_AGE_GROUPS",
    "DEFAULT_MAX_POPULATION_ALLOCATION_BUILDINGS",
    "DEFAULT_MAX_RESIDENTIAL_CAPACITY_SUBJECTS",
    "DemographicScenario",
    "DemographicScenarioError",
    "PopulationAllocationDiagnostics",
    "PopulationAllocationError",
    "PopulationAllocationResult",
    "PopulationAllocationStatus",
    "PopulationAllocator",
    "PopulationTarget",
    "PopulationTargetKind",
    "ResidentialBuildingCapacity",
    "ResidentialCapacityCalculator",
    "ResidentialCapacityError",
    "ResidentialCapacityResult",
    "ResidentialCapacitySubject",
]
