"""Stable coarse stage identities shared by core adapters and later orchestration."""

PREPARE_SNAPSHOT_STAGE = "prepare_snapshot"
EVALUATE_CONSTRAINTS_STAGE = "evaluate_constraints"
SUITABILITY_STAGE = "suitability"
ZONING_STAGE = "zoning"
ROADS_STAGE = "roads"
BLOCKS_AND_PARCELS_STAGE = "blocks_and_parcels"
BUILDINGS_STAGE = "buildings"
DEMOGRAPHY_STAGE = "demography"
INFRASTRUCTURE_STAGE = "infrastructure"
FINAL_VALIDATION_STAGE = "final_validation"
METRICS_STAGE = "metrics"
PERSIST_MANIFEST_STAGE = "persist_manifest"

CANONICAL_STAGE_ORDER = (
    PREPARE_SNAPSHOT_STAGE,
    EVALUATE_CONSTRAINTS_STAGE,
    SUITABILITY_STAGE,
    ZONING_STAGE,
    ROADS_STAGE,
    BLOCKS_AND_PARCELS_STAGE,
    BUILDINGS_STAGE,
    DEMOGRAPHY_STAGE,
    INFRASTRUCTURE_STAGE,
    FINAL_VALIDATION_STAGE,
    METRICS_STAGE,
    PERSIST_MANIFEST_STAGE,
)

CANONICAL_STAGE_DEPENDENCIES: dict[str, tuple[str, ...]] = {
    PREPARE_SNAPSHOT_STAGE: (),
    EVALUATE_CONSTRAINTS_STAGE: (PREPARE_SNAPSHOT_STAGE,),
    SUITABILITY_STAGE: (EVALUATE_CONSTRAINTS_STAGE,),
    ZONING_STAGE: (SUITABILITY_STAGE,),
    ROADS_STAGE: (ZONING_STAGE,),
    BLOCKS_AND_PARCELS_STAGE: (ROADS_STAGE,),
    BUILDINGS_STAGE: (BLOCKS_AND_PARCELS_STAGE,),
    DEMOGRAPHY_STAGE: (BUILDINGS_STAGE,),
    INFRASTRUCTURE_STAGE: (DEMOGRAPHY_STAGE, ROADS_STAGE),
    FINAL_VALIDATION_STAGE: (INFRASTRUCTURE_STAGE,),
    METRICS_STAGE: (FINAL_VALIDATION_STAGE,),
    PERSIST_MANIFEST_STAGE: (METRICS_STAGE,),
}
